networks:
  ates:
    driver: bridge

version: '3.8'

services:
  auth:
    build: ./auth
    container_name: ates_auth
    command: >
      bash -c "uvicorn auth:app --reload --host 0.0.0.0 --port 8881"
    volumes:
      - ./:/auth
    networks:
      - ates
    ports:
      - 8881:8881
    environment:
      - DEBUG=1
  frontoffice:
    build: ./frontoffice
    container_name: ates_fo
    command: >
      bash -c "uvicorn frontoffice:app --reload --host 0.0.0.0 --port 8882"
    volumes:
      - ./:/frontoffice
    networks:
      - ates
    ports:
      - 8882:8882
    environment:
      - DEBUG=1
  inventory:
    build: ./inventory
    container_name: ates_inventory
    command: >
      bash -c "uvicorn inventory:app --reload --host 0.0.0.0 --port 8883"
    volumes:
      - ./:/inventory
    networks:
      - ates
    ports:
      - 8883:8883
    environment:
      - DEBUG=1
  inventory-consumer:
    build: ./inventory
    container_name: ates_inventory_consumer
    command: python3 inventory/consumer.py
    volumes:
      - ./:/inventory
    networks:
      - ates
    environment:
      - DEBUG=1
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.1
    hostname: zookeeper
    container_name: zookeeper
    networks:
      - ates
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-server:5.4.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    networks:
      - ates
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://broker:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
